name: Python Package

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt
          pip install -e .[dev]  # This installs dev dependencies like pytest

      - name: Run tests
        run: |
          pytest tests/ --disable-warnings  # Runs all tests in the `tests` directory

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
